stages:
  - build
  - deploy

build project:
  stage: build
  image: node:latest
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/

netlify:
  stage: deploy
  image: node:latest
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir-build --prod
