stages:
  - test
  - build

test project:
  image: node:latest
  script:
    - yarn install
    - yarn test

build project:
  image: node:latest
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/


  
