stages:
  - test
  - build

test project:
  image: node:15
  script:
    - yarn install
    - yarn test

build project:
  image: node:15
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/

netlify:
  stage: deploy
  image: node:15
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir-build --prod

  
